@startuml gameBoard
skinparam Style strictuml
skinparam SequenceMessageAlignment center
actor Player
gameController -> gameBoard : getBoard
gameController <-- gameBoard : getBoard
Player -> gameController : move
gameController -> ship : hit
gameController <-- ship : hit
@enduml